### ISSUE TITLE
Attempted Removal of cooldown script and winrm check script fails when reboot not required

### ISSUE THREAD

**Issue by JimFicarra** [trondhindenes/ansibleroles-winreboot#1]
Firstly, great work on development of this role!  I found a minor issue that has an easy fix.
# Issue Description

When a reboot is not required, the tasks in /tasks/main.yml attempt to remove the cooldown and winrm check scripts in /tmp on the control server.  This fails because the previous tasks to check if the cooldown and winrm check scripts exist do not run because the conditional only allows them to run if a reboot is required as determined by the win_pendingreboot module in the library folder.

Therefore, cooldownstat and winrmstat variables are never registered and checking cooldownstat.stat.exists and winrmstat.stat.exists failes with 'dict object' has no attribute 'state'
# Resolution

I removed the conditionals that check the cooldown and winrm check scripts so they always run.
## Before (cooldown)

```
- name: Check if cooldown script exists
  stat:
    path="/tmp/{{ inventory_hostname }}_cooldown.sh"
  register: cooldownstat
  ignore_errors: True
  delegate_to: 127.0.0.1
  changed_when: False
  when: pending_reboot_output.pending_reboot == true

- name: Remove existing cooldown script
  file:
    name="/tmp/{{ inventory_hostname }}_cooldown.sh"
    state=absent
  delegate_to: 127.0.0.1
  changed_when: False
  when: cooldownstat.stat.exists is defined  and cooldownstat.stat.exists and pending_reboot_output.pending_reboot == true
```
## After (cooldown)

```
- name: Check if cooldown script exists
  stat:
    path="/tmp/{{ inventory_hostname }}_cooldown.sh"
  register: cooldownstat
  ignore_errors: True
  delegate_to: 127.0.0.1
  changed_when: False

- name: Remove existing cooldown script
  file:
    name="/tmp/{{ inventory_hostname }}_cooldown.sh"
    state=absent
  delegate_to: 127.0.0.1
  changed_when: False
  when: cooldownstat.stat.exists is defined  and cooldownstat.stat.exists and pending_reboot_output.pending_reboot == true
```
## Before (winrm check)

```
- name: Check if winrm check script exists
  stat:
    path="/tmp/{{ inventory_hostname }}.sh"
  register: winrmstat
  ignore_errors: True
  delegate_to: 127.0.0.1
  changed_when: False
  when: pending_reboot_output.pending_reboot == true

- name: Remove existing winrm check script
  file:
    name="/tmp/{{ inventory_hostname }}.sh"
    state=absent
  delegate_to: 127.0.0.1
  changed_when: False
  when: winrmstat.stat.exists is defined  and winrmstat.stat.exists and pending_reboot_output.pending_reboot == true 
```
## After (winrm check)

```
- name: Check if winrm check script exists
  stat:
    path="/tmp/{{ inventory_hostname }}.sh"
  register: winrmstat
  ignore_errors: True
  delegate_to: 127.0.0.1
  changed_when: False

- name: Remove existing winrm check script
  file:
    name="/tmp/{{ inventory_hostname }}.sh"
    state=absent
  delegate_to: 127.0.0.1
  changed_when: False
  when: winrmstat.stat.exists is defined  and winrmstat.stat.exists and pending_reboot_output.pending_reboot == true 
```
